### ISSUE TITLE
Assistant installing mods as raw files, not DLLs

### ISSUE THREAD

**Issue by smurfhunter** [knah/VRCMelonAssistant#24]
Found an issue myself and a few other users have experienced an issue where the assistant downloads mods as files with 2-3 digit file names and no file type. This results in no mods launching. Renaming the numbered files to give them the .dll type results in mods launching as expected.

**Comment by rakosi2** [comment]
This may be related to #23

**Comment by DubyaDude** [comment]
Reverted URL change on API/v0, should work again

**Comment by smurfhunter** [comment]
:')
