### ISSUE TITLE
Headpats not well received.

### ISSUE THREAD

**Issue by EntityReborn** [knah/VRCMelonAssistant#3]
Clicking on headpats results in a crashing stacktrace.

**Comment by luludotdev** [comment]
![image](https://user-images.githubusercontent.com/2358182/125871649-0e54767a-43d2-41f3-b8a0-92ecb9f6a2d0.png)

**Comment by knah** [comment]
Clicking on headpats/hugs no longer crashes, but error boxes will just chill there until they get fixed or removed in upstream.
